/**
 * Smart wallet address → display name (BullX stream + PumpFun WS).
 * Multiple addresses may share one display name (e.g. DAVE PORTNOY).
 * Generated in part by scripts/merge-kol.mjs (kol-base + wallets-import).
 */

export const KOL_NAMES = {
  "1cKYst38AiSvLsxWQ5PibkBZHCsC7vZWvYSMenonteX": "crime sider 3",
  "1d1467rpAnFDJhrJdKn5RcFNKig13kHV7GMQcpoVbTN": "gas",
  "215nhcAHjQQGgwpQSJQ7zR26etbjjtVdW74NLzwEgQjP": "ogant",
  "286CHN57Km41GsAnDv866WKd6YB6HPSjFgF4rGDJTRLf": "great trencher",
  "2DqZ2NiezXJUGJ4LpHALKb8P3RDgTRVAANUqcYYWBPW6": "wunder or domi",
  "2G86foXQaSJRwgSgjsXrDxkLFvnPTCDVfZWm9rwQbB9E": "slingor",
  "2MX6VMS2DHCeRdGitcdg3VphaduKGwGskbae4CMwHBHd": "kur",
  "2NxsrGQtXNr3LSWRt3bDDoymA921j2FNxeoh3MhowJ3M": "good wallet",
  "2WZDv5VKV5xebGBVkQqkd8D3SFpSPBTud9wTuVW7ZrDn": "ryder?",
  "2fg5QD1eD7rzNNCsvnhmXFm5hqNgwTTG8p7kQ6f3rx6f": "cupseyy",
  "2j1aLVjdccpe8UYCkKJGvD2krXLn6XbZrtvc94oquFe8": "mil100x",
  "2mM4rHrUkShVE6xXePv6wbaPki3XKTwePCvv86LTFrTW": "gas",
  "2mukkMvbsXtDhpZqsLtvRcnFMt5nRo9SBH5P6f6DBT43": "big h",
  "2pUUZYtokRgDV2YzL6M5pjb1jyoHE367yU1sdQ7ac3ea": "log",
  "38ph918ic2DqNMMT3q6jTweG6ohPSFXqwNLoqHJefASg": "1ly",
  "3D4vwvLxuyrpjk64umXhRZjDBx2pDPKbqMVQoKy23HbB": "wunder",
  "3MnUjz71DXnxkPBpN5xDtmjDkRwPVWoHKoiBazu2CMrs": "pfp",
  "3RZ1Gnxxwfy1wsKVtS2UA59C657dnaoonokAX8AM57hZ": "smokez",
  "3gzGKxWmJTocvVhZ4ndkmAuMMko9DwKtL4Ch5z6MygYj": "momo",
  "3kShLyrTSz6NYc2XBHq6RVoMA4Hh8g39Bxrdf3Ki45TG": "mmb",
  "3kebnKw7cPdSkLRfiMEALyZJGZ4wdiSRvmoN4rD1yPzV": "BASTILLE",
  "3v8mNVUrKsyRs2PUcoFfEY5of4zzRscahpkstGLgmGLS": "DANI",
  "3yHuUFXvfaT923XQyyRun4AoTLByRM6RQgsaHoK9guPw": "ILY4",
  "3zD1armVsd4UUDW4RvcaE4ve6oEkmGyHPEjtB7q5Q9LU": "marcell",
  "444FRosEym9fziB9A3AFSDJkqfrfVVfnzw5gE5G5w444": "lex",
  "46PbpBKFMSBdUZanqZh1tHp3FerppqFdNmb19sfXFB4g": "alpha",
  "48dHnrjBZtWriWaYFNPavpTPYCHcUGhd9iUYdYqHBzou": "sling side",
  "498g1rVnFcnjBjpfw1xyqA1WvgQXUU8RWuELjxkjAayQ": "frank degods",
  "4BdKaxN8G6ka4GYtQQWk4G4dZRUTX2vQH9GcXdBREFUk": "jijo",
  "4Be9CvxqHW6BYiRAxW9Q3xu1ycTMWaL5z8NX4HR3ha7t": "MITCH",
  "4BukjaBiZgGaha6iniWDLiMRsLPCLxAyGMyjnkM3oPmR": "BIG DAN",
  "4MNMt96NGVTWLp221tFdkFMfiFUXcBV5gh3zjyZF1icY": "telson",
  "4ceeiMAmoeCms8hY9DPmLtrXV4RYJeRVhHmmFEpCJEzg": "kur",
  "4en4pDsvVyPsEVrvQy4KLXRbJbN949a7zPgxsrtMqu43": "Meme creator",
  "4gUmTFuZkKFs31fcoYQPz9Sug8kzWpMHSpL9rRf6owfn": "telson",
  "4nHfhix85yKjBve9wfBMFf1ygF7duQ8ntvkeWC31XYES": "spongebob",
  "4sgd7efDkAWuZWE9BYHLyXHuPu8V8DmvvZro45BN8mdm": "momo",
  "5B52w1ZW9tuwUduueP5J7HXz5AcGfruGoX6YoAudvyxG": "yenni",
  "5BdjRxQnTDJLC8GM6qi1hmmTMntyxTYJywdYUHdo87an": "kerson??",
  "5LjV6jjZbzw5ZmrgzdWvMtxYpbjAXrVaKjDrJebgEbtM": "sling side",
  "5XVKfruE4Zzeoz3aqBQfFMb5aSscY5nSyc6VwtQwNiid": "hy",
  "5hDFMh6ZNFa3dUjn9PYwnzkbaxRfwCGGm18ZhNH4Z5xB": "ILY2",
  "5maoLqFTfy5wKevfLELYFAsWuSiMSbdSVT6HLFtSwg5m": "dx pip",
  "5pak98tekBYRu9oguVi2N8pJo5rKzcBMMb8eidVtDPX9": "orangiebot",
  "5rkPDK4JnVAumgzeV2Zu8vjggMTtHdDtrsd5o9dhGZHD": "portnoy",
  "5skKDVJ77jhEa1YELXuARCdMLTupVSt83c6VxAYbYqpg": "POSSIBLE ALPHA",
  "5srrQETcW1zR2JkaKuUzjcUKjZZSoJx21HneyhLN5bNT": "Logurt",
  "5t9xBNuDdGTGpjaPTx6hKd7sdRJbvtKS8Mhq6qVbo8Qz": "smokez",
  "689PgJFtc6AJRvnCGNzhiHYfRjpbaxsAMvE2kLL819vW": "nice trader bot",
  "69QhmNbiiCJHyZXejckLJEu7NZNwF5cNZaoFDqTmyJfh": "HAWKY ONLY",
  "6AqXjwS4d1PnpWP7Zyd9FZNAb485rUFQM4G71EgcB9Tg": "vet",
  "6Ddty7rXjofMzUARBreu16T9rANFKkBNzwKh8f5v9rfm": "leon",
  "6Eegkyd2qNzxSzZz3PH3jiDyqL5HFcHdcsb9zfMzWHKB": "the duve",
  "6UDyYZbt7WGiecGUTZcPxFARtGG6vKxxPgtSGpwuqkvA": "SCANNOORS WALLET",
  "6aXkVrC9V66AVhZxCgwcxRmGvWwyrhhVCx8uB3wqM3n8": "mid",
  "6bDfvuFnx6T6sVuvLuQtNRTAYroMjKEXU7AUpPidiEwA": "jerm",
  "6cmX7gTeRD1gP9AsMixUqXw4e9DRCrwBQocr54e34TbR": "momo",
  "6hb1nVBisukdBKWHrT5wxvJHrQWjNC4chjJBDzDFTtwJ": "wunder",
  "6mWEJG9LoRdto8TwTdZxmnJpkXpTsEerizcGiCNZvzXd": "SLINGOR",
  "6nhskL8RVpXzWXC7mcC1UXpe3ze2p6P6og1jXVGUW88s": "PATTY ICE",
  "73LnJ7G9ffBDjEBGgJDdgvLUhD5APLonKrNiHsKDCw5B": "wadles",
  "76ZUBj1JLz7arTVHSRJok5oSTEqDuVBgySFMVHtzxzZc": "crime",
  "7KdQsWEbxeXfwzPwP178RPLBRrtz31jvMFYiPhD5f3W3": "leao",
  "7MXdhkgWG3NMVi3CbQSjGhsYk9XjC1fDppDoQgPeJmYa": "WHALEEEEE",
  "7Z9299Cqy1Qpb88mqJmR6hV35r7HJpNWWhvjJfbebFPe": "domi",
  "7azv99nzG6KYzkAP3uTN7trfUFtEqzXw1Pxy8MsR8R6P": "insider",
  "7eNRALuXYUJkUWTvRj5tcB7tcT43kmT5SNdkfy9fKTto": "pow",
  "7hhSfNuGHxntWtRHN6sGsK8xmqCGVv1nxHy1APcfV2go": "Clipper wallet",
  "7ygKTWqrBkE48v4jEnC5zH3cuKnTCZAkzmE2ZYQuegV9": "troll top holder",
  "85R9ibxPASU3hDtomwsh6e4Z4u6UXqmGQKT5grWRBL2f": "tele",
  "87rRdssFiTJKY4MGARa4G5vQ31hmR7MxSmhzeaJ5AAxJ": "dior",
  "88e2kBDJoN7eQCBj2sxT15etUZ3jPNzD4ijCs1TNySWJ": "troll top holder",
  "8Cqz51drzDxGzgEYmpdZwLcGoguF6jSdnKRK1ZWV87T4": "kur",
  "8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6": "WHALEE",
  "8fSnLTnRViK83dDesivTsPx2wiRhwti9xoafeMGjEyLJ": "gremlin",
  "8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR": "Casino",
  "8sfbKCYFvKuzG6vE5dAyHrSVxEgRWgMrcjUEvfhYr4ng": "koyla",
  "8yJFWmVTQq69p6VJxGwpzW7ii7c5J9GRAtHCNMMQPydj": "LEXAPRO",
  "8zFZHuSRuDpuAR7J6FzwyF3vKNx4CVW3DFHJerQhc7Zd": "traderpow",
  "94EeAexcdVStbA8MHwVujkNkUpDD5sWKpLiSDDtyps6H": "bot??",
  "96gLpkdSGRB6SjArBwv5vhfoAZ4S3ij4hyvxtLmUsqGP": "wasta",
  "9CDiPtpPF2xB1VRsR13NeULzuU3X7xirfbqhZWmKcPqJ": "TEST ADDY",
  "9ERucopM8icQLi2dUScxdLAoMVhPGKzXEtyKqd1gYhz8": "kur",
  "9GTVJLduxXwUR6otWSYgDLatYJCab61wHB8Vcoi2FNEf": "ELITE FNF4",
  "9HTA8PwuB9ck5R9d6pMHdpkcSzFxAonDGBvHBhKokKPQ": "domi",
  "9Rf8Yyd7Awz9pCxt2X5iLHxMo7JrQagNPB7rhy8qfTT6": "kerson",
  "9Zq837L1KhWcFy5A4twRkA2XsSms7nrELujpu3hKS1DB": "jerm",
  "9bJ9AvkTkadgeFLWgHrYLfHhRYq4dBX5iAgbMA9ez9qk": "dior",
  "9e1KnkZ8Uz5UAABtYLzu3Yya7VpXnGcmcw4vEK8cETFA": "67",
  "9iUkBohJTLkkmz14V3pgM5ukmk1rbjFzYN1EHEohLZSn": "crime sider 2",
  "9vfHbSJ9EDzhHxpSV9Trd1EWQ1SyB928RwPGFXwWxnT1": "momo",
  A4DCAjDwkq5jYhNoZ5Xn2NbkTLimARkerVv81w2dhXgL: "millions",
  AAgJUUvdsjU33GDNLQJ1ubFVMqKjbQo6mTsYzz78EF3H: "ryder",
  ACHhRQMbTxuWqU3bmbBbgUNGsPsYnvB8KLcPkkXCY1C7: "MARCELL",
  ACkYoPDWnbMN7TB8xujinD8K9qhoSAGVvdW9ViD31V3h: "wunder",
  AE6aJVPyx1APTQQ1aatbFXceNFbtq1GSXV6W2jhVu5hV: "degen??",
  AQF1BPKmsBDd6ECbJK7ELpWTs18GfamKFQew3sWUu5kz: "domi",
  AUGFKJMqXcbj2LWf9tLG8W69yFwRqZyZMzCcPmhx9bTT: "inu",
  AVAZvHLR2PcWpDf8BXY4rVxNHYRBytycHkcB5z5QNXYm: "ansem",
  AX9yHrwoMTFoio9yNiLPrH65u6nqKi2dfNg9tjdBEr9W: "marcell",
  AXd4sN54ERMc4ZqhGnJx2vYRmwcDE2PcQGngaudpvsMg: "GTON",
  AZNsezb13699fivitS3fic5MYrpZJtm6wc989zXQp9Zy: "momo",
  AcViiH6zCub6f5rm8tr7peEKp92TvYkAvGGw7cfAmnPD: "Jeet wallet",
  AjmmrnMkd4FHe7HZULcof2WZaR7x2ivdvNJwGcLJz2YS: "andy",
  AoEDMxKnY7gUsB9cpqsYm7kZhPs7i3SfcVon2r9iiBTh: "cupsey sider",
  As9AU5b2nq3DqtwaDRikVarw1fKrBd3A7bSDKq4SW5Xb: "ricci",
  Aw4mqCCzte1mEsutsd2XEp7uP7hPCdM4qqJykRTUi8HJ: "masons",
  AxEYT4Ny3DL3wGeyLBufmWMnmYtJwBfgMQM5XY5QhRnL: "mil",
  B3wagQZiZU2hKa5pUCj6rrdhWsX3Q6WfTTnki9pJwzMh: "XANDER",
  BAsFeSAnnauM5hrdyxS3Urs3gXHMDfuiSxWEMkmRUkoR: "LOGURT",
  BC8yiFFQWFEKrEEj75zYsuK3ZDCfv6QEeMRif9oZZ9TW: "wrld",
  BCagckXeMChUKrHEd6fKFA1uiWDtcmCXMsqaheLiUPJd: "DV",
  BEZodb5aE2RRfgjSdAhhjDBL5VhHoEejrEcLUQ97Em3c: "tele",
  BH8K9x9qjhsqE9BdjY3jZx8Hsh6yhFJ8V6RStRoM2b9f: "kerson",
  BKBF7uAkknfR9naLkVGadCEy6QUdrZGVPYKcWeweVMmW: "momo",
  BNahnx13rLru9zxuWNGBD7vVv1pGQXB11Q7qeTyupdWf: "Good trader",
  BNi39xV18hnyq9tSCJkr1eeDSYXi2Nj8CW4tEwLb6UcD: "spongebob",
  BYw5AEo7TBwdFZRGJtRKy9qYQiXNeF9CLTBV3J4pEgP4: "dv2",
  BcHJmd3QK1Z2GxjQT4zymmiixRtfogUvfHR2gQo5ErWW: "rocket",
  Be24Gbf5KisDk1LcWWZsBn8dvB816By7YzYF5zWZnRR6: "chairman",
  Bf4zji6S979QySiGNjPJ2VMZ5i2SRVtAzfx8QUBScJm6: "crow",
  BfiayGKtENxCvpYjJnaTuLN8XdELm44vXDqWRouvxzGM: "leao",
  Bp9EzaEhWMVJhs1NgsCaRFFj28BbwDkyYrNJMzRp14Aj: "domi",
  Bq5N5kQYFDT9ZNE3CaZL519oyYbS3TokSspouzqJvKjR: "koyla",
  BrBekCSxU9Fqad5FgcAP6n7H7qf3AYM91ic4yQX3AZa8: "slinggcr",
  BtMBMPkoNbnLF9Xn552guQq528KKXcsNBNNBre3oaQtr: "letterbomb",
  BtdWod3uER6nJarnHXDFRSFLi4WnvU9DDPxchSY7aSmN: "telson",
  BtkFpES41nrkA9bqXpQ8yiYUKinVFcysrNF5MWfogKip: "lord?",
  Bym1vDAP31BzDVNQ5wYrS6pGqVM1LqRAKhMgAkFezJtr: "ava",
  C7magzRms4BQuhDHFZ1zryi5DmmDPbRE2B5ZK1UhPvR: "momo",
  CEoJPnnCfYisckyJnqZLeefc559KeheVsFLbpfDuTPWo: "cented",
  CFigJbHQuZuVZotVTcV6s2Esm98uDxifDW8Lu2LbtDr7: "kur",
  CMd8R5xjkoS9eoVFtc5CTcRrs34baN2uGvdpyjTbXwH8: "ryder",
  CNudZYFgpbT26fidsiNrWfHeGTBMMeVWqruZXsEkcUPc: "gake side",
  CPD19xKjuffyCiLRJejVDyN5jtbCUkU7DBZoxXGrXy9K: "wunder",
  CRVidEDtEUTYZisCxBZkpELzhQc9eauMLR3FWg74tReL: "FRANKDEGODS",
  CTL3vpKTM4E1mo1PmzVL38TLpk4owt7CiQvB45LzL1Gd: "idarsu",
  CUnovtRHzkLDXhRuJm3a9FjhdVdyY1KcySRPdiomiQDD: "insider",
  CV9uvgiNq1MGTWg6gR7Y4weCLymawsGrPupnCtuNe8AS: "wunderrr",
  CcgcFLV29qmgCxH8R2edjew8VGeRSQAgr2iDAKoUsjfP: "ILY3",
  CmhQNMAhwcQdxtGe9dB2cF3Schd2mxXrrNB4fTpQH2Rr: "telson",
  CoyuPaYaFpqABZ8KJKxJrjDADzuRPY4TVg9McGV2B1rs: "cathy",
  CpUtxdqkytpn3qu7qoRfatwuPjRQ68WKiGWzmtfMYqTG: "kala",
  Cxe1d5zFifK4a4UZoHQaCK7sfqd84XjcKy1qtjnz3bge: "DJEN",
  CyaE1VxvBrahnPWkqm5VsdCvyS2QmNht2UFrKJHga54o: "CENTEDD",
  CzhpWb4CqhTA4MuATiCqeHZUWKPLY2HZkmerGj48WpEM: "ELITE FNF3",
  D2r9m8nkoHXaeuy6m3r8F1wtEuE31Kv94kPjzM3wouz4: "ryder fomo",
  D2wBctC1K2mEtA17i8ZfdEubkiksiAH2j8F7ri3ec71V: "Dior",
  D5ThFoVy5frnhbqd1BJ9HsZLMxxdEutCyuBuNNFzcsmY: "ricci",
  D7xK1ZLz8KQNWN8aU1jbzNAuT5xwqgFrCUUYodVU4G42: "the duve",
  DEdEW3SMPU2dCfXEcgj2YppmX9H3bnMDJaU4ctn2BQDQ: "solomon",
  DLo33RBKaRDwHDqX3oa6bU2pXoVTv7KCeU8oaMiWUHL: "IJ",
  DNfuF1L62WWyW3pNakVkyGGFzVVhj4Yr52jSmdTyeBHm: "GAKE",
  DUEaqZZZ1o6Ft2xu4JE2QtvnFxwAg16qzU7pYnBW3Yhr: "MAX",
  DXU65912VjiPUhKR37TLiHCrbp4uNHVNNZiBdLv1uAx1: "ily",
  DZAa55HwXgv5hStwaTEJGXZz1DhHejvpb7Yr762urXam: "EARLY WHALE",
  DZdQfZpwURDNENmDyeWZuexCmbR99MGZ9wQEMYCHwLWd: "telesuer",
  Dej7gkwMRNfawGQtRQ6ofuP9gmjNfbcZxR2RmfaBbG23: "kur",
  DfMxre4cKmvogbLrPigxmibVTTQDuzjdXojWzjCXXhzj: "euris",
  DuQabFqdC9eeBULVa7TTdZYxe8vK8ct5DZr4Xcf7docy: "orangie",
  E6HNiAPLDj8tVYBP7JsKrGT5ZygnLGeNX9hG7aGojdZ3: "momo",
  E8FzSTJBZdK1C4bwcEBceCEE1BrbqGsi2ApzUh6ZUwUX: "lex",
  EQ3o3xuyP5BSr5oM7YoAkkC2crBdpunsRLCdY8fvi14P: "zap",
  EjaMRoxyHFSLdMtRtXLtinT96mTHhEdp9jubVubwWtxr: "djen??",
  EnQLCLB7NWojruXXNopgH7jhkwoHihTpuzsrtsM2UCSe: "ERIK STEPHENS",
  EpTPPrqzQUgtJaZ7XUUiK3nuHe1MusbjLiQuJx3kNnL6: "treasuredavid",
  EwTNPYTuwxMzrvL19nzBsSLXdAoEmVBKkisN87csKgtt: "gake alts",
  F482fEf8wNLu8PnK7a5sUTvWNJsTG8M6cTXH8RLc7zYX: "slap",
  F4CBgrxVhq8wQ6cgEnU4AnKCC2V4RsktYwUvxkkb1k1Q: "satoshi",
  F58N26fjLL9FwqLYyhGaGw6LCpaPcxC5kE5LzWRa5C4c: "momo",
  F8zzkLu9sV5Wc3VsMs1Wu9QiBuf2rEBWXD873x5vuQEr: "wunder",
  FDntYdBVqVhXJ2NTQt2rhRdGBiDaAM61vXSoGFn7bfmD: "kur",
  FFBNzyxw9TR8YDRakUbyePJ1VG8Lmbs4xTj7p2nBWWNa: "Loggypoo",
  FJPcSA14q3wewdZzfPCLU9CNoMERDBBnqNSsyiQiB2UJ: "slingor side",
  FVugAb5gWb6vz3zUppNoC5gWvbVA5xDGKnL9tTmTnxsU: "bruce",
  FXzJ6xwH2HfdKshERVAYiLh79PAUw9zC7ucngupt91ap: "DAVE PORTNOY",
  FZU56d9iPqohXM5XBrYYBZLi2UoUnZT4V5Qf2631tEzb: "good guy",
  FcR3gTgviX1zARVrJNp4dg1PHwz5ocvx5dbCaJQZThbs: "leao",
  Fdv3EQykFyxFpDf6SFB9TuaWdVFtmZeav3hrhrvQzZbM: "TOLY WALLET",
  FfyLxGLJu6WnCMahP9AKEDkC3VFWRvcH8wUx42CQTGhB: "daumen",
  FfztZq1outrYfyYbKw5P4LGo4xUc4XYEdf7o91UdS7qu: "wendy",
  Fhk1Q5FSKbFJi3Zxr5sexGm76QfeQpB6RzPYrhvKKo3g: "jerm?",
  FixmSpsBa7ew26gWdiqpoMAgKRFgbSXFbGAgfMZw67X: "marcell",
  FmNYjPAuak5zG9oVTdDRrh3YSetY1HzcwYY8trje6E7R: "bonk coins",
  FrBSudKWbY4uaWvzzKyhuausrFFZ5RJvKN8piHAEzTuM: "jerm",
  FrQ59KmKUhu8G3KnDz5sDQzhnqPGBn41WSM3EN634J3S: "MARCEL2",
  FvPEk72M6Lp78idz5fbgXZijvaRPgXJGkkJs21hBSWJD: "HUP",
  G2YxRa6wt1qePMwfJzdXZG62ej4qaTC7YURzuh2Lwd3t: "ASH",
  G3Mnr9w617qXk8UqxDHYQt3dBkpY7vVpETUAdY6UuqkX: "sling side",
  G3g1CKqKWSVEVURZDNMazDBv7YAhMNTjhJBVRTiKZygk: "YT STREAMER",
  G9bKTpofSp75E1fwCLyqVnk1Dt93D1RBxtDNkfBHwJ7n: "rozayy",
  GGYPBCB4MchekxzBWEfbtrW2CSGmdLvUdCnmBP1MUSTo: "crime sider 4",
  GKCAprYubBG6ikjtmHFwqm8a7tWNUBVFYwmnsuD2hmM3: "wunder",
  GPsdQQDYewZuYjG6u2fhvpTbPce9kKfoSE4usNLZUXPU: "satoshi",
  GR5oGTsAodBMYHXA1d1WcFRcrE2y8LfrPcjiAN7RPgEg: "clint",
  GVUoC2tG4gx27LqLeL2dA7jL3FhKJpAfJukLejZM7NSb: "Logurt2",
  GVysQ8UMjUHVUq3LWj4fy9HbcXAyo9q58oNRismApPjd: "gas",
  GXNotAsWJsG7e9bKYfkENiPC7N6SDLNsKPaDGhBPUorB: "kur",
  GY3d9LzFQp1EUVuPyUW1wUtinUMoLNpJrQa3YFyW2Wgg: "alfa",
  Geoh8ukirhCpusvVU6yHgaKFNVWfkGDznmDqxcS8k8b4: "kur",
  GfqZxpzeAQb5ppUCKaUkQCDS86nu5pwjQXty59MhaZgK: "chaddy",
  GijFWw4oNyh9ko3FaZforNsi3jk6wDovARpkKahPD4o5: "ELITE FNF1",
  Gjcr5r54zqMCPXnQVxacpN9m4YVVAcs4DBi5tVS4VjLF: "crime sider",
  GpaxwRPnFsygJaw1d9uf78Tzt7yDoZr5hBhfWEk7gyRT: "BATMANWIF",
  GtRL3uSeFgJx8Xe7FtCcoU2xzC5E1CAgb77njgQhvjBL: "hawk active again",
  H2jn39eZQFnLPQrhVA9DJytTsERfNG7wzBuPozgo3Tbg: "hupppp",
  HDdwH8RNzk1MFPDgdPMxhfMEAoXYngdDcRGmsXz9tEis: "Clipper wallet",
  HDi4tV7XcEJPGBzL1qz63TdiPLhaYEZkDdcAACh3z29a: "mil",
  HGHv7YvHBtN7cG3em1RXTNFhS3LXMWsSf6WPuapaBukv: "ITAY FRONTRUN",
  HHL4ZoXzu4kD8AydeNmFWooWQ75iC6bfJixE5Q1KrfyC: "tele",
  HJhDs7gJjZN2hTzxf7QCZVVrnmQYqTpySHxWum9EtWE4: "lord?",
  HL3FZ8XWnLnn1HuktmgpNRyFRjuAxWbXNQVj5fPPzZwt: "HIGH PNL WR",
  HYMmhz7YBGHLtcvULf2UJSb7Du8p6XFHC3wB3CVeoHm7: "ryder fs",
  HYWo71Wk9PNDe5sBaRKazPnVyGnQDiwgXCFKvgAQ1ENp: "owari",
  HYhEYgKpiUgioP7mbzekiHHaMwfYmofi5LUQZ8ZxxwUT: "Trader",
  HYonGF8NEF7VefYomAat9TH8ZNAUzcwUYBsW2yUva5Eq: "kace",
  HYqMCUf24LCh2Q6BCvzTzePJ1tzMWUVCTjiJ86JYjEBv: "size",
  HdxkiXqeN6qpK2YbG51W23QSWj3Yygc1eEk2zwmKJExp: "itai",
  HetnuaUUbBjFCx5wFYoiQuTRmDFKbEwqj1z4MsEJ1jYf: "auris 2",
  Hm5EBf3Jx2WkUHXNY5sADtrAjUmRAKrM31nkqZUFnGxg: "marcell",
  Hqz6oNWW3m8sFFbiZoFF9ijeVzbPKpshkM587jHCAgqP: "sling sude",
  HugksxcSGZnhfTuLuwnP38E94FX3HjWZfiNjiXSdx6Yh: "gremlin2",
  J5SvVzdmogaLAZWYkiEHiXLR4BGRYVfydgd7LpM1SBa5: "kur",
  J9TYAsWWidbrcZybmLSfrLzryANf4CgJBLdvwdGuC8MB: "??",
  JDd3hy3gQn2V982mi1zqhNqUw1GfV2UL6g76STojCJPN: "west",
  JHSYHMKnVB9R7MpnBzt8ZtpiyixTu1uevVE6xeS1rmv: "koyla 2",
  Pops2mhXqVqquhaoTw6Tt8ZtbpvcsvRsp12uXy2XB8Z: "LOGURTAXIOM",
  RFSqPtn1JfavGiUD4HJsZyYXvZsycxf31hnYfbyG6iB: "Alvin Patty",
  RUrTjuEqBLDgeauh51V6ygWG1Qw7EVkPXs8UMSrsKgb: "bossman",
  VJSDW6S74YXR4rRR9P4xwhMvLZJQMhrUb8XMFirUsy1: "bot trader",
  dumbU7CxBpL7ifuRFaQmae299uh8xzVpUXUL7bRMjRf: "Pump wallet",
  jRgy6dB3PwUFctM6VSGUMc2pQwnM2VVEgmoAEDTdj3F: "kasey",
  oACNLDVNoMoaPzNbSNAZ1uzUF8FhBF2xgtd7uDohgjN: "koyla",
  p8EHRZEsfPMrDL2ENdy72uHuRuLRLxGYCV7NyogKngx: "wp",
  suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK: "CUPSEY",
  vQ33AcEii7mciXznW7TAqzpv18Z77PQHxSfJ7xNBHwU: "MARCEL",
};

/** Unique display names for the filter checklist (legacy order first, then A–Z). */
export const ALL_KOL_NAMES = [
  "BATMANWIF",
  "TEST ADDY",
  "ERIK STEPHENS",
  "MARCEL",
  "BASTILLE",
  "MITCH",
  "XANDER",
  "BIG DAN",
  "FRANKDEGODS",
  "TOLY WALLET",
  "PATTY ICE",
  "DAVE PORTNOY",
  "POSSIBLE ALPHA",
  "WHALEEEEE",
  "GAKE",
  "CUPSEY",
  "DANI",
  "ELITE FNF4",
  "ELITE FNF3",
  "ILY4",
  "ILY3",
  "ILY2",
  "MARCEL2",
  "MARCELL",
  "ELITE FNF1",
  "LEXAPRO",
  "ITAY FRONTRUN",
  "SCANNOORS WALLET",
  "LOGURTAXIOM",
  "Logurt2",
  "DJEN",
  "LOGURT",
  "Logurt",
  "Loggypoo",
  "EARLY WHALE",
  "HIGH PNL WR",
  "??",
  "1ly",
  "67",
  "alfa",
  "alpha",
  "Alvin Patty",
  "andy",
  "ansem",
  "ASH",
  "auris 2",
  "ava",
  "big h",
  "bonk coins",
  "bossman",
  "bot trader",
  "bot??",
  "bruce",
  "Casino",
  "cathy",
  "cented",
  "CENTEDD",
  "chaddy",
  "chairman",
  "clint",
  "Clipper wallet",
  "crime",
  "crime sider",
  "crime sider 2",
  "crime sider 3",
  "crime sider 4",
  "crow",
  "cupsey sider",
  "cupseyy",
  "daumen",
  "degen??",
  "dior",
  "Dior",
  "djen??",
  "domi",
  "DV",
  "dv2",
  "dx pip",
  "euris",
  "frank degods",
  "gake alts",
  "gake side",
  "gas",
  "good guy",
  "Good trader",
  "good wallet",
  "great trencher",
  "gremlin",
  "gremlin2",
  "GTON",
  "hawk active again",
  "HAWKY ONLY",
  "HUP",
  "hupppp",
  "hy",
  "idarsu",
  "IJ",
  "ily",
  "insider",
  "inu",
  "itai",
  "Jeet wallet",
  "jerm",
  "jerm?",
  "jijo",
  "kace",
  "kala",
  "kasey",
  "kerson",
  "kerson??",
  "koyla",
  "koyla 2",
  "kur",
  "leao",
  "leon",
  "letterbomb",
  "lex",
  "log",
  "lord?",
  "marcell",
  "masons",
  "MAX",
  "Meme creator",
  "mid",
  "mil",
  "mil100x",
  "millions",
  "mmb",
  "momo",
  "nice trader bot",
  "ogant",
  "orangie",
  "orangiebot",
  "owari",
  "pfp",
  "portnoy",
  "pow",
  "Pump wallet",
  "ricci",
  "rocket",
  "rozayy",
  "ryder",
  "ryder fomo",
  "ryder fs",
  "ryder?",
  "satoshi",
  "size",
  "slap",
  "sling side",
  "sling sude",
  "slinggcr",
  "SLINGOR",
  "slingor",
  "slingor side",
  "smokez",
  "solomon",
  "spongebob",
  "tele",
  "telesuer",
  "telson",
  "the duve",
  "Trader",
  "traderpow",
  "treasuredavid",
  "troll top holder",
  "vet",
  "wadles",
  "wasta",
  "wendy",
  "west",
  "WHALEE",
  "wp",
  "wrld",
  "wunder",
  "wunder or domi",
  "wunderrr",
  "yenni",
  "YT STREAMER",
  "zap"
];

export const KOL_WALLET_ADDRESSES = Object.freeze(Object.keys(KOL_NAMES));
